[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "txvideolike_obfuscated"
version = "1.0.0"
description = "Obfuscated version of txvideolike"
requires-python = ">=3.8" 